version: "3"

services:
  postgresql:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRESQL_PASSWORD=postgres
    ports:
      - "5432:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "8081:8080"
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgresql:5432/keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
    depends_on:
      - postgresql

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
