apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name | trunc 63 | trimSuffix "-" }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          env:
            - name: RE_SERVERPORT
              value: "{{ .Values.serverPort }}"
            - name: RE_DATABASE__HOST
              value: "{{ .Values.database.host }}"
            - name: RE_DATABASE__PORT
              value: "{{ .Values.database.port }}"
            - name: RE_DATABASE__USER
              value: "{{ .Values.database.user }}"
            - name: RE_DATABASE__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}-secret
                  key: database-password
            - name: RE_DATABASE__DBNAME
              value: "{{ .Values.database.dbname }}"
            - name: RE_OIDC__PROVIDER_URL
              value: "{{ .Values.oidc.provider_url }}"
            - name: RE_OIDC__CLIENT_ID
              value: "{{ .Values.oidc.client_id }}"
            - name: RE_OIDC__CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}-secret
                  key: oidc-client-secret
            - name: RE_OIDC__REDIRECT_URL
              value: "{{ .Values.oidc.redirect_url }}"
