apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
type: Opaque
data:
  database-password: {{ .Values.database.password | b64enc | quote }}
  oidc-client-secret: {{ .Values.oidc.client_secret | b64enc | quote }}
