info:
  contact: {}
paths:
  /ping:
    get:
      consumes:
      - application/json
      description: get a pong response
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Pong
      tags:
      - example
swagger: "2.0"
