info:
  contact: {}
paths:
  /ping:
    get:
      consumes:
      - application/json
      description: get a pong response
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Pong
      tags:
      - example
  /reports/download:
    get:
      consumes:
      - application/json
      description: Downloads an Excel report containing transactions and their associated
        labels.
      produces:
      - application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
      responses:
        "200":
          description: Excel report
          schema:
            type: file
      security:
      - BearerAuth: []
      summary: Download Report
      tags:
      - reports
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
